defaults:
  - hydra: default
  - datamodule: point_cloud_datamodule
  - loss: cfd_loss_wrapper
  - metric: cfd_metric_wrapper
  - model: transformer
  - _self_

log_dir: "log/train/${now:%Y%m%d_%H%M%S}"
logger: ""

seed: 42
devices: [0]
precision: "bf16-mixed"

datamodule:
  train_split_file: "dataset/DrivAerNetPP/split/train_split.json"
  test_split_file: "dataset/DrivAerNetPP/split/test_split.json"
  train_downsample_size: ${downsample_size}
  test_downsample_size: ${downsample_size}

metric:
  mean_std_file: "dataset/DrivAerNetPP/mean_std.json"

ckpt_file: ""
resume: false

num_epochs: 100
batch_size: 8
downsample_size: 5_0000

test_interval: 1
save_interval: 10

train_dataloader:
  batch_size: ${batch_size}
  num_workers: 16
  pin_memory: true
  shuffle: true
  drop_last: true
  prefetch_factor: 16

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  weight_decay: 0.01

lr_scheduler:
  max_lr: ${optimizer.lr}
  pct_start: 0.1
  anneal_strategy: "cos"
  div_factor: 1.0e4
  final_div_factor: 1.0e-3

test_dataloader:
  batch_size: 8
  num_workers: 16
  pin_memory: true
  shuffle: false
  drop_last: false
  prefetch_factor: 16
